export const projects = [
  {
    id: "1",
    title: "Pong",
    description: "Ce petit projet était le premier projet réaliser à l'IUT. Ce dernier consistait à coder le jeu Pong à l'aide du langage Processing (dérivé de Java).",
    cahierDesCharges: "Réaliser le jeu pong à l'aide de Processing. Ajouter un mode 2 joueurs. Un mode avec plusieurs balles et des obstacles",
    resultatLivre: "le projet a étais rendu avec toutes les fonctionnalités requise",
    methodeOutilsUtilise: "Travail réalisé à l'aide du langage Processing est de l'IDE éponyme. Utilisation des tableaux, classes et fonctions.",
    image: "pong.png",
    link: "pong",
  },
  {
    id: "2",
    title: "Lowatem",
    description: "Ce projet, réalisé en Java consistait à implémenter les règles d'un jeu imaginaire au fur et à mesure.",
    cahierDesCharges: "test",
    resultatLivre: "etsset",
    methodeOutilsUtilise: "test",
    image: "Kirby.png",
    link: "lowatem",
  },
  {
    id: "3",
    title: "Database",
    description: "Ce projet consistait à designer et créer une base de données selon les besoins d'un clients à l'aide du langage SQL. Il fallait aussi réaliser une maquette du logiciels livré à l'entreprise.",
    cahierDesCharges: "",
    resultatLivre: "",
    methodeOutilsUtilise: "",
    image: "",
    link: "database",
  },
  {
    id: "4",
    title: "Management",
    description: "Ce projet consistait à créer une entreprise dans le domaine du numérique, en prenant en compte toutes les contraintes lui a sa création (rentabilité, marketing, légal...).",
    cahierDesCharges: "",
    resultatLivre: "",
    methodeOutilsUtilise: "",
    image: "",
    link: "Management",
  },
  {
    id: "5",
    title: "Web",
    description: "Ce projet consistait à designer et coder un site vitrine pour l'entreprise créer dans le projet précédent le site devait ếtre responsive et réalisé seulement avec HTML et CSS.",
    cahierDesCharges: "",
    resultatLivre: "",
    methodeOutilsUtilise: "",
    image: "",
    link: "web",
  },
  {
    id: "6",
    title: "Virtual Machine",
    description: "Ce projet consistait à installer sur une Machine Virtuelle une distribution Linux avec un environnement graphique léger, et d'installer les logiciels dont le clients a besoins (Git, Rust nightly, VS code)",
    cahierDesCharges: "",
    resultatLivre: "",
    methodeOutilsUtilise: "",
    image: "",
    link: "virtualMachine",
  },
];


export default projects;