export const projects = [
  {
    id: "1",
    title: "Bash Converter",
    description: "This project involved creating a .pdf to .html file converter using the Bash language. The project was to be completed in a group of 2 people.",
    cahierDesCharges: "The script was intended to convert pdf and audio files into web pages containing screenshots of each pdf page and corresponding audio excerpt based on a storyboard file.",
    resultatLivre: "The script was delivered with different conversion options, a storyboard file, and a README used as a user manual.",
    methodeOutilsUtilise: "To complete this project, we used the Bash language, VS Code, and Git.",
    image: "bash-converter.png",
    link: "bash-converter",
  },
  {
    id: "2",
    title: "Graphs and Algorithms",
    description: "This project involved applying graph algorithms on a customizable graph.",
    cahierDesCharges: "The project was to be completed in Java, using Maven and the JBotSim library. The project required implementation of breadth-first search and A* algorithms.",
    resultatLivre: "The deliverable for this project was a .jar file and the javaDoc.",
    methodeOutilsUtilise: "To complete this project, we used Java, Maven, JBotSim, IntelliJ, and Git.",
    image: "graphes.png",
    link: "graphes",
  },
  {
    id: "3",
    title: "POP3 Client",
    description: "The goal of the project was to develop a graphical POP3 Client in C#.",
    cahierDesCharges: "The project was to be completed in a group of 3 and had to implement a mail service with a POP3 client and a TCP server.",
    resultatLivre: "The deliverable for this project was a functional application that allows retrieving emails",
    methodeOutilsUtilise: "To complete this project, we used C#, Visual Studio, and Git.",
    image: "pop3.png",
    link: "client-pop3",
  },
  {
    id: "4",
    title: "RSA Encryption/Decryption program",
    description: "The goal of this project is to create a program using a chosen language that allows encrypting and decrypting messages using the RSA method.",
    cahierDesCharges: "Working in a group of 2, the project required creating a program that allows encrypting and decrypting messages using the RSA method.",
    resultatLivre: "The deliverable for this project was a functional Python program that allows encrypting and decrypting messages with a command-line interface.",
    methodeOutilsUtilise: "To complete this project, we used Python, VS Code, and Git.",
    image: "rsa.png",
    link: "rsa",
  },
  {
    id: "5",
    title: "MiniShell",
    description: "The goal of this project is to create a mini shell in C.",
    cahierDesCharges: "This project was to be completed in a group of 3, and was to be created in C using signals and pipes.",
    resultatLivre: "The deliverable for this project was a functional mini shell with several standard commands such as 'ls', 'cd'...",
    methodeOutilsUtilise: "To complete this project, we used C, VS Code, and Git.",
    image: "minishell.png",
    link: "minishell",
  },
  {
    id: "6",
    title: "BloomFilter",
    description: "The goal of this project is to implement the Bloom Filter data structure in Java.",
    cahierDesCharges: "This project, to be completed alone, had to implement a Bloom filter that can store Strings, check if a String is present in the filter and perform performance benchmarks of the filter.",
    resultatLivre: "The deliverable for this project was a functional Maven project with benchmarks and their interpretations.",
    methodeOutilsUtilise: "To complete this project, I used Java, Maven, IntelliJ, Git, and the 'jmh.Benchmark' library to perform the benchmarks.",
    image: "bloomFilter.png",
    link: "bloomfilter",
  },
];


export default projects;